tap "cloudflare/cloudflare"
tap "homebrew/bundle"
tap "nextdns/tap"
tap "teamookla/speedtest"
# Plugin manager for zsh, inspired by oh-my-zsh and vundle
brew "antigen"
# C library for encoding, decoding, and manipulating JSON
brew "jansson"
# Emacs dependency management
brew "cask"
# Command-line tool for Amazon Route 53
brew "cli53"
# Tool that bootstraps your dotfiles
brew "dotbot"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# GNU compiler collection
brew "gcc"
# Distributed revision control system
brew "git"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# 'traceroute' and 'ping' in a single tool
brew "mtr"
# Port scanning utility for large networks
brew "nmap"
# Platform built on V8 to build network applications
brew "node"
# Tool for managing your YubiKey configuration
brew "ykman"
# Download YouTube videos from the command-line
brew "youtube-dl"
# Fork of youtube-dl with additional features and fixes
brew "yt-dlp"
# Command-line tool for the YubiKey PIV application
brew "yubico-piv-tool"
# Cloudflare Tunnel
brew "cloudflare/cloudflare/cloudflared"
# NextDNS DNS/53 to DoH Proxy
brew "nextdns/tap/nextdns"
# Ookla Speedtest
brew "teamookla/speedtest/speedtest"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Command-line interface for 1Password
cask "1password-cli"
# Desktop password and login vault
cask "bitwarden"
# Desktop client for GitHub repositories
cask "github"
# Tool to optimize images to a smaller size
cask "imageoptim"
# System monitoring app
cask "istat-menus"
# Password manager app
cask "keepassxc"
# Host-based application firewall
cask "little-snitch"
# Online collaborative whiteboard platform
cask "miro"
# German banking and financial management software
cask "moneymoney"
# VPN client
cask "mullvadvpn"
# App to write, plan, collaborate, and get organized
cask "notion"
# Instant messaging application focusing on security
cask "signal"
# Music streaming service
cask "spotify"
# Open-source code editor
cask "visual-studio-code"
# Multimedia player
cask "vlc"
# Video communication and virtual meeting platform
cask "zoom"
